theme = "hugo-sugoi"
baseURL = "https://vobetz.github.io"
languageCode = "en-us"
title = "Home"
summaryLength = 20
paginate = 5
# Google Analytics ID, Uncomment below line to enable
# googleAnalytics = "UA-123-45"

# Enter your disqus Shortname and uncomment below line to enable
# disqusShortname = "yourdiscussshortname"

[params]
favicon = "images/favicon.png"
herotitle = "The Data of Humans"
herolink = "https://scholar.google.com/citations?user=sYILIrcAAAAJ"
herolinktext = "Academic Publications"
contact = "Send me a message and I will get back as soon as possible."

[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-code'></i>"
        url     = "about"
        weight  = -2
    [[menu.nav]]
        name    = "projects"
        pre = "<i class='fas fa-chart-area'></i>"
        url     = "post"
        weight  = -3
    [[menu.nav]]
        name    = "contact"
        pre = "<i class='fas fa-envelope'></i>"
        url     = "contact"
        weight  = -1
